Update azure-static-web-apps-witty-grass-09a172510.yml

diff --git a/.github/workflows/azure-static-web-apps-witty-grass-09a172510.yml b/.github/workflows/azure-static-web-apps-witty-grass-09a172510.yml
--- a/.github/workflows/azure-static-web-apps-witty-grass-09a172510.yml
+++ b/.github/workflows/azure-static-web-apps-witty-grass-09a172510.yml
@@ -27,14 +27,25 @@ jobs:
         uses: Azure/static-web-apps-deploy@v1
         with:
           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_GRASS_09A172510 }}
-          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
+          repo_token: ${{ secrets.GITHUB_TOKEN }}
           action: "upload"
-          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
-          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
-          app_location: "/" # App source code path
-          api_location: "" # Api source code path - optional
-          output_location: "/" # Built app content directory - optional
+          app_location: "/"
+          api_location: ""
+          output_location: "/"
           ###### End of Repository/Build Configurations ######
+      - name: Check Deployment Sanity
+        run: |
+          URL="https://witty-grass-09a172510.3.azurestaticapps.net/"
+      
+          STATUS=$(curl -s -o /dev/null -w "%{http_code}" $URL)
+      
+          if [ "$STATUS" -eq 200 ]; then
+            echo "Deployment sanity check passed. Status code: $STATUS"
+          else
+            echo "Deployment sanity check failed. Status code: $STATUS"
+            exit 1
+          fi
+
 
   close_pull_request_job:
     if: github.event_name == 'pull_request' && github.event.action == 'closed'
